### ISSUE TITLE
Eventkort viser ikke arrrangement med lange titler?

### ISSUE THREAD

**Issue by frubl0m** [det-akadmeiske-kvarter/infoskjerm#5]
Opplevde at eventkortene ikke viste arrangement som har lange titler - vet ikke hva dette kommer av. Gjaldt spesifikt "Up&Coming, Lone Child og You're Such A Shining Star, But It All Ends With Balendro"

Andre arrangement samme dag funket

**Comment by mathiash98** [comment]
Ser ut til å virke hos meg.
Har du mer informasjon om eventet? Kan ha vært noe med klokkeslett osv?

![localhost_8080_](https://user-images.githubusercontent.com/5204006/55794246-104c3e00-5ac5-11e9-827e-91cfd4f24cd9.png)

**Comment by frubl0m** [comment]
Hm! Så riktig ut der - men er dette dummydata eller rett i appen? Kan være noe med modulen som henter dataen

**Comment by frubl0m** [comment]
Fant ut av det!

"Teglverket + Stillhet/Backstage" mangler fra listen deres over rom i utils.js, jeg har lagt det til nå

**Comment by mathiash98** [comment]
Supert 🥇  burde kanskje lagt inn at om det er et rom som ikke er med i dataene blir lagt til i f.eks. 1.etg
